In [54]:
from robopy.base.serial_link import SerialLink
from robopy.base.serial_link import Revolute
import numpy as np

In [55]:
initialPose_left = np.deg2rad([0, 0, 0])

In [56]:
links = [Revolute(d=0.2,a=0, alpha = np.pi/2,j=0, theta=0, offset=0, qlim =initialPose_left[0]+np.deg2rad([-90, +90])),
         Revolute(d=0, a=0.4, alpha = 0,j=0, theta=0, offset=0, qlim =initialPose_left[1]+np.deg2rad([-20, +90])),
         Revolute(d=0,a=0.4, alpha = 0,j=0, theta=0, offset=0, qlim =initialPose_left[0]+np.deg2rad([-90, +90]))]

In [57]:
baseL = np.matrix([[1, 0, 0, 0],
                [0, 1, 0, 0],
                [0, 0, 1, 0],
                [0, 0, 0, 1]])

In [58]:
leftArm = SerialLink(links,'3Z',baseL,colors='Red')

In [59]:
t_min = []
t_max = []
for i in range(len(links)):
    t_min.append(links[i].qlim[0])
    t_max.append(links[i].qlim[1])

In [60]:
N = 3000
t1 = t_min[0] + (t_max[0]-t_min[0]) * np.random.rand(N,1)
t2 = t_min[1] + (t_max[1]-t_min[1]) * np.random.rand(N,1)
t3 = t_min[2] + (t_max[2]-t_min[2]) * np.random.rand(N,1)

In [61]:
Y = np.hstack((t1,t2,t3))

In [62]:
T =[]
for i in range(0,N):
    T.append(leftArm.fkine(Y[i]))

In [63]:
T_array = []
for i in range(0, len(T)):
    T_array.append(np.array(T[i]))


In [90]:
T_array[0]

array([[ 3.37429519e-01, -5.98170181e-01,  7.26865706e-01,
         2.71146865e-01],
       [ 3.57124671e-01, -6.33084294e-01, -6.86779620e-01,
         2.86973218e-01],
       [ 8.70978352e-01,  4.91321393e-01,  6.12323400e-17,
         8.95788540e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [104]:
R_array = []
for i in range(len(T_array)):
    for j in range(0,3):
        R_array.append(T_array[i][j][0:3])

In [106]:
T_array[0]

array([[ 3.37429519e-01, -5.98170181e-01,  7.26865706e-01,
         2.71146865e-01],
       [ 3.57124671e-01, -6.33084294e-01, -6.86779620e-01,
         2.86973218e-01],
       [ 8.70978352e-01,  4.91321393e-01,  6.12323400e-17,
         8.95788540e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [107]:
R_array[0]

array([ 0.33742952, -0.59817018,  0.72686571])