In [128]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input
from keras.wrappers.scikit_learn import KerasRegressor
import numpy as np
from keras import backend as K
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split


In [129]:
data_x = np.loadtxt("X.csv", delimiter=',')

In [130]:
data_y = np.loadtxt('Y.csv',delimiter=",")

In [131]:
data_x

array([[-0.41874 ,  0.53503 , -0.10177 ,  2.0425  ,  1.1827  , -1.5708  ],
       [-0.070826, -0.15355 ,  0.80943 ,  1.8929  , -0.87139 ,  1.5708  ],
       [ 0.15848 ,  0.024527,  0.90977 ,  0.99655 ,  0.068314,  1.5708  ],
       ...,
       [ 0.49651 ,  0.31286 ,  0.42368 ,  0.38948 ,  0.42217 ,  1.5708  ],
       [-0.16902 ,  0.34117 ,  0.87346 ,  1.435   ,  1.4802  ,  1.5708  ],
       [-0.092157,  0.11429 ,  0.80619 ,  1.9888  ,  0.81443 ,  1.5708  ]])

In [132]:
data_y

array([[ 1.9589  ,  0.13682 , -1.2359  ],
       [-0.87139 ,  0.6126  ,  1.2803  ],
       [ 0.068314,  1.2078  , -0.21124 ],
       ...,
       [ 0.42217 ,  0.18046 ,  0.20902 ],
       [ 1.4802  ,  0.76543 ,  0.66959 ],
       [ 0.81443 ,  0.64549 ,  1.3433  ]])

In [133]:


X_train, X_test, y_train, y_test = train_test_split(data_x, data_y, test_size=0.2, random_state=42)

In [ ]:
loss = []
def base_model():
     model = Sequential()
     model.add(Dense(32,activation='relu'))
     model.add(Dense(64,activation='relu'))
     model.add(Dense(128,activation='relu'))
     model.add(Dense(32,activation='relu'))
     model.add(Dense(3, init='normal'))
     model.compile(loss='mean_absolute_error', optimizer = 'adam', metrics=['accuracy'])
     model.summary()
     return model

In [ ]:

clf = KerasRegressor(build_fn=base_model, epochs=500, batch_size=20,verbose=2)

In [ ]:
clf.fit(X_train,y_train)

In [188]:
res = clf.predict(X_test)

In [189]:
clf.score(X_train,y_train)

-0.018403173393259444

In [190]:
clf.model.save('qnew3000_5e3.h5')

In [191]:
score = mean_absolute_error(y_test, res)

In [192]:
score

0.020208844636336334

In [193]:
data_xx = np.loadtxt("XX.csv", delimiter=',')

In [194]:
q_new = clf.predict(data_xx)

In [195]:
q_new

array([[ 2.834503  ,  0.9744889 , -0.75455123],
       [ 2.9196386 ,  1.1822226 , -0.96565133],
       [ 2.9374669 ,  1.3901622 , -1.205993  ],
       [ 2.8838646 ,  1.6267931 , -1.5756372 ],
       [ 2.7711205 ,  1.8312261 , -1.915173  ],
       [ 2.5686257 ,  2.0037122 , -2.2375016 ],
       [ 2.3223884 ,  2.0029063 , -2.396414  ],
       [ 2.1056838 ,  1.9315834 , -2.4294274 ],
       [ 1.853258  ,  1.695997  , -2.3911972 ],
       [-1.4687966 , -0.02416579, -0.07829185],
       [-1.314397  , -0.0654919 , -0.00952603],
       [-1.1590391 , -0.11563711,  0.06244029],
       [-0.99471116, -0.16275744,  0.12136905],
       [-0.8178574 , -0.17503981,  0.14753118],
       [-0.6411147 , -0.18161972,  0.16939223],
       [-0.4630729 , -0.18175913,  0.18040562],
       [-0.2829393 , -0.17984897,  0.18859245],
       [-0.12326489, -0.18635279,  0.21013801],
       [ 0.05872101, -0.15630214,  0.15209481],
       [ 0.24227025, -0.09546339,  0.09226413],
       [ 0.47661328, -0.03951795,  0.032

In [196]:
import pandas as pd

In [197]:
df = pd.DataFrame(data=q_new)

In [198]:
df.to_csv('q_new10.csv',header=False,index= False)